### ISSUE TITLE
Open to a higher-level package?

### ISSUE THREAD

**Issue by matthewmueller** [a8m/tree#13]
Hey, thanks for creating this library! I'm using it in tests, but getting it all setup takes a bit more code than I would have liked.

Would you be open to exposing a `Print` function in this repository that has the following?

```go
package tree

type fs struct{}

func (f *fs) Stat(path string) (os.FileInfo, error) {
	return os.Lstat(path)
}
func (f *fs) ReadDir(path string) ([]string, error) {
	dir, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	names, err := dir.Readdirnames(-1)
	dir.Close()
	if err != nil {
		return nil, err
	}
	return names, nil
}

func Print(dir string) string {
	b := new(bytes.Buffer)
	tr := tree.New(dir)
	opts := &tree.Options{
		Fs:      new(fs),
		OutFile: b,
	}
	tr.Visit(opts)
	tr.Print(opts)
	return b.String()
}
```

**Comment by ncw** [comment]
The definition of `fs` should probably be factored out of `cmd/tree` and into a new sub package, say `ostree` or something like that.

That would remove most of the boiler plate from your example.

I think that this `ostree` package could have a `Print` function

What do you think?

**Comment by a8m** [comment]
> I think that this `ostree` package could have a Print function

Sounds good to me, go ahead and create a PR with @ncw's proposal.
