### ISSUE TITLE
Include Option --prune

### ISSUE THREAD

**Issue by patgmiller** [a8m/tree#17]
@a8m On your list of task to add all options, #1, I notice you don't have `--prune` which is simply to exclude empty directories from the output. Here's the man page details on it.

```
--prune
              Makes tree prune empty directories from the output, useful when used in conjunction with -P or -I.
```

I am wondering is there a specific reason you don't include it. I am willing to work on implementing it.

**Comment by patgmiller** [comment]
I've added the `--prune` option here, [patgmiller/tree/compare/17-add-options](https://github.com/patgmiller/tree/compare/17-add-options). I'm also looking to add `--matchdirs`.

**Comment by a8m** [comment]
Hey @patgmiller,
You're welcome to create a PR for adding this.

cc @ncw

**Comment by a8m** [comment]
Closed with https://github.com/a8m/tree/pull/18
