### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by toddy15** [a8m/tree#7]
Hi,

I've noticed that you've stated in the README that the code is licensed under MIT. However, an explicit license file with the license text is missing. Could you please add that file?

Regards,
Tobias

**Comment by a8m** [comment]
Hey @toddy15,
Thanks for opening this issue.
I'll add this in the next few days, but of course you're always welcome to send a PR.

**Comment by toddy15** [comment]
There you go ... :-) #8

**Comment by a8m** [comment]
Thanks @toddy15 😃
